export type City = 'milano' | 'roma' | 'torino';
export type ContractType =
  | 'locazione-3-2-canone'
  | 'locazione-transitoria-canone'
  | 'locazione-studenti-universitari';

export interface RequiredSpec {
  step3: string[];
  step4: string[];
}

/** Baseline requireds compiled from the specs you pasted. */
export const REQUIRED_REGISTRY: Record<City, Record<ContractType, RequiredSpec>> = {
  milano: {
    'locazione-3-2-canone': {
      step3: [
        'tipologia_locazione_11_5',
        'mobilio_porzione_11_5',
        'spazi_comuni_31_6',
        'durata_anni_2_6',
        'data_decorrenza_locazione_3_1_3_3_6',
        'importo_mensile_locazione_6_5',
        'pagamento_canone_3_2_6',
        'metodo_pagamento_34_6',
        'domanda_spese_condominiali_1_5',
        'spese_4_2_6',
        'domanda_utenze_6_3',
        'utenze_12_3',
        'domanda_cauzione_15_5',
        'cauzione_locazione_12_5',
        'garanzie_accessorie_5_2_6',
        'domanda_garante_19_2',
        'garante_dati_19_2',
        'domanda_recesso_conduttore_2_4',
        'recesso_conduttore_1_2_5',
        'cedolare_secca_6_7',
        'mobilio_12_2_6',
        'domanda_elenco_arredi_intero_7',
        'elenco_arredi_lista_intero_7',
        'domanda_elenco_arredi_porzione_6',
        'elenco_arredi_lista_porzione_6',
        'blocco_immobile_29',
        'domanda_pertinenze_14_2_6',
        'pertinenze_16_2_6',
        'domanda_ape_1_5',
        'numero_attestato_prestazione_energetica_3_6',
        'locatore_4_3_6',
        'conduttore_4_3_6',
        'domanda_note_50_2',
        'note_49_2',
        'luogo_di_sottoscrizione_contratto_4_2_6',
        'data_di_sottoscrizione_contratto_4_2_6'
      ],
      step4: ['tipologia_locazione_20_4', 'indicazione_stanza_5', 'tipologia_contratto_14_5', 'domanda_arredi_12', 'domanda_note_22_5', 'note_34_5_1_1_1_2_1_1_7']
    },
    'locazione-transitoria-canone': {
      step3: [
        'locazione_intera_o_parziale_8_2_6',
        'mobilio_porzione_9_7',
        'spazi_comuni_29_7',
        'esigenza_transitorieta_1_2_6',
        'natura_transitoria_conduttore_1_2_6',
        'natura_transitoria_locatore_1_2_6',
        'durata_mesi_2_7',
        'data_decorrenza_locazione_3_1_3_1_2_2_7',
        'importo_mensile_locazione_5_5',
        'pagamento_canone_giorno_2_7',
        'metodo_pagamento_33_6',
        'domanda_spese_condominiali_5_5',
        'spese_6_7',
        'domanda_utenze_15_3',
        'utenze_31_3',
        'domanda_cauzione_14_5',
        'cauzione_locazione_10_5',
        'garanzie_accessorie_7_2_7',
        'domanda_garante_3_2',
        'garante_dati_3_2',
        'cedolare_secca_14_7',
        'preavviso_recesso_conduttore_2_1_2_7',
        'mobilio_14_2_7',
        'domanda_elenco_arredi_intero_10',
        'elenco_arredi_lista_intero_10',
        'domanda_elenco_arredi_porzione_7',
        'elenco_arredi_lista_porzione_7',
        'blocco_immobile_51',
        'domanda_pertinenze_15_2_7',
        'pertinenze_23_2_7',
        'domanda_ape_13',
        'numero_attestato_prestazione_energetica_1_2_7',
        'locatore_10_2_7',
        'conduttore_10_2_7',
        'domanda_note_65_2',
        'note_64_2',
        'luogo_di_sottoscrizione_contratto_3_1_2_7',
        'data_di_sottoscrizione_contratto_3_1_2_7'
      ],
      step4: ['tipologia_locazione_20_4', 'indicazione_stanza_5', 'tipologia_contratto_14_5', 'domanda_arredi_12', 'domanda_note_22_5', 'note_34_5_1_1_1_2_1_1_7']
    },
    'locazione-studenti-universitari': {
      step3: [
        'locazione_intera_o_parziale_8_2_1_6',
        'mobilio_porzione_9_2_6',
        'spazi_comuni_29_2_6',
        'corso_di_studi_2_8',
        'durata_mesi_2_1_8',
        'data_decorrenza_locazione_3_1_3_1_2_2_1_7',
        'importo_mensile_locazione_4_6',
        'pagamento_canone_giorno_2_1_8',
        'metodo_pagamento_35_7',
        'domanda_cauzione_13_6',
        'cauzione_locazione_8_6',
        'domanda_spese_condominiali_6_6',
        'spese_6_1_8',
        'domanda_utenze_8_3',
        'utenze_16_3',
        'garanzie_accessorie_7_2_1_8',
        'domanda_garante_14_2',
        'garante_dati_14_2',
        'domanda_recesso_conduttore_5_5',
        'preavviso_recesso_conduttore_2_1_2_1_7',
        'cedolare_secca_14_1_8',
        'mobilio_14_2_1_8',
        'domanda_elenco_arredi_intero_20',
        'elenco_arredi_lista_intero_20',
        'domanda_elenco_arredi_porzione_15',
        'elenco_arredi_lista_porzione_15',
        'blocco_immobile_38',
        'domanda_pertinenze_15_2_1_8',
        'pertinenze_23_2_1_8',
        'domanda_ape_2_5',
        'numero_attestato_prestazione_energetica_1_2_1_7',
        'locatore_10_2_1_8',
        'conduttore_10_2_1_8',
        'domanda_note_58_2',
        'note_57_2',
        'luogo_di_sottoscrizione_contratto_3_1_2_1_8',
        'data_di_sottoscrizione_contratto_3_1_2_1_8'
      ],
      step4: ['tipologia_locazione_20_4', 'indicazione_stanza_5', 'tipologia_contratto_14_5', 'domanda_arredi_12', 'domanda_note_22_5', 'note_34_5_1_1_1_2_1_1_7']
    },
  },

  roma: {
    'locazione-3-2-canone': {
      step3: [
        'tipologia_locazione_11',
        'mobilio_porzione_11',
        'spazi_comuni_31',
        'durata_anni_2',
        'data_decorrenza_locazione_3_1_3_3',
        'importo_mensile_locazione_6',
        'pagamento_canone_3_2',
        'metodo_pagamento_34',
        'domanda_spese_condominiali_1',
        'spese_4_2',
        'domanda_utenze_6',
        'utenze_12',
        'domanda_cauzione_15',
        'cauzione_locazione_12',
        'garanzie_accessorie_5_2',
        'domanda_garante_19',
        'garante_dati_19',
        'domanda_recesso_conduttore_2',
        'recesso_conduttore_1_2',
        'cedolare_secca_6',
        'mobilio_12_2',
        'domanda_elenco_arredi_intero_1',
        'elenco_arredi_lista_intero_1',
        'domanda_elenco_arredi_porzione',
        'elenco_arredi_lista_porzione',
        'comune_immobile_7',
        'blocco_immobile_24',
        'domanda_pertinenze_14_2',
        'pertinenze_16_2',
        'domanda_ape_1',
        'numero_attestato_prestazione_energetica_3',
        'locatore_4_3',
        'conduttore_4_3',
        'domanda_note_50',
        'note_49',
        'luogo_di_sottoscrizione_contratto_4_2',
        'data_di_sottoscrizione_contratto_4_2',
      ],
      step4: ['tipologia_locazione_20', 'indicazione_stanza', 'tipologia_contratto_14', 'domanda_arredi', 'domanda_note_22', 'note_34_5_1_1_1_2_1_1'],
    },
    'locazione-transitoria-canone': {
      step3: [
        'locazione_intera_o_parziale_8_2',
        'mobilio_porzione_9',
        'spazi_comuni_29',
        'esigenza_transitorieta_1_2',
        'natura_transitoria_conduttore_1_2',
        'natura_transitoria_locatore_1_2',
        'durata_mesi_2',
        'data_decorrenza_locazione_3_1_3_1_2_2',
        'importo_mensile_locazione_5',
        'pagamento_canone_giorno_2',
        'metodo_pagamento_33',
        'domanda_spese_condominiali_5',
        'spese_6',
        'domanda_utenze_15',
        'utenze_31',
        'domanda_cauzione_14',
        'cauzione_locazione_10',
        'garanzie_accessorie_7_2',
        'domanda_garante_3',
        'garante_dati_3',
        'cedolare_secca_14',
        'preavviso_recesso_conduttore_2_1_2',
        'mobilio_14_2',
        'domanda_elenco_arredi_intero_16',
        'elenco_arredi_lista_intero_16',
        'domanda_elenco_arredi_porzione_13',
        'elenco_arredi_lista_porzione_13',
        'comune_immobile_9',
        'blocco_immobile_58',
        'domanda_pertinenze_15_2',
        'pertinenze_23_2',
        'domanda_ape',
        'numero_attestato_prestazione_energetica_1_2',
        'locatore_10_2',
        'conduttore_10_2',
        'domanda_note_65',
        'note_64'
      ],
      step4: ['tipologia_locazione_20', 'indicazione_stanza', 'tipologia_contratto_14', 'domanda_arredi', 'domanda_note_22', 'note_34_5_1_1_1_2_1_1'],
    },
    'locazione-studenti-universitari': {
      step3: [
        'locazione_intera_o_parziale_8_2_1',
        'mobilio_porzione_9_2',
        'spazi_comuni_29_2',
        'corso_di_studi_2',
        'durata_mesi_2_1',
        'data_decorrenza_locazione_3_1_3_1_2_2_1',
        'importo_mensile_locazione_4',
        'pagamento_canone_giorno_2_1',
        'metodo_pagamento_35',
        'domanda_cauzione_13',
        'cauzione_locazione_8',
        'domanda_spese_condominiali_6',
        'spese_6_1',
        'domanda_utenze_8',
        'utenze_16',
        'garanzie_accessorie_7_2_1',
        'domanda_garante_14',
        'garante_dati_14',
        'domanda_recesso_conduttore_5',
        'preavviso_recesso_conduttore_2_1_2_1',
        'cedolare_secca_14_1',
        'mobilio_14_2_1',
        'domanda_elenco_arredi_intero_27',
        'elenco_arredi_lista_intero_27',
        'domanda_elenco_arredi_porzione_22',
        'elenco_arredi_lista_porzione_22',
        'comune_immobile_8',
        'blocco_immobile_45',
        'domanda_pertinenze_15_2_1',
        'pertinenze_23_2_1',
        'domanda_ape_2',
        'numero_attestato_prestazione_energetica_1_2_1',
        'locatore_10_2_1',
        'conduttore_10_2_1',
        'domanda_note_58',
        'note_57',
        'luogo_di_sottoscrizione_contratto_3_1_2_1',
        'data_di_sottoscrizione_contratto_3_1_2_1'
      ],
      step4: ['tipologia_locazione_20', 'indicazione_stanza', 'tipologia_contratto_14', 'domanda_arredi', 'domanda_note_22', 'note_34_5_1_1_1_2_1_1'],
    },
  },

  torino: {
    'locazione-3-2-canone': {
      step3: [
        'durata_anni',
        'data_decorrenza_locazione_3_1_3',
        'importo_mensile_locazione_12',
        'pagamento_canone_3',
        'metodo_pagamento_31',
        'domanda_spese_condominiali_2',
        'spese_4',
        'domanda_utenze_2',
        'utenze_4',
        'domanda_cauzione_19',
        'cauzione_locazione_20',
        'garanzie_accessorie_5',
        'domanda_garante_20',
        'domanda_recesso_conduttore_1',
        'recesso_conduttore_1',
        'cedolare_secca_17',
        'mobilio_12',
        'domanda_elenco_arredi_intero_8',
        'elenco_arredi_lista_intero_8',
        'blocco_immobile_30',
        'domanda_pertinenze_14',
        'pertinenze_16',
        'domanda_ape_6',
        'numero_attestato_prestazione_energetica',
        'locatore_4',
        'conduttore_4',
        'domanda_note_51',
        'note_50',
      ],
      step4: ['tipologia_contratto_18', 'domanda_arredi_1', 'domanda_note_34', 'note_34_5_1_1_1_2_1_1_1'],
    },
    'locazione-transitoria-canone': {
      step3: [
        'esigenza_transitorieta_1',
        'natura_transitoria_conduttore_1',
        'natura_transitoria_locatore_1',
        'durata_mesi',
        'data_decorrenza_locazione_3_1_3_1_2',
        'importo_mensile_locazione_11',
        'pagamento_canone_giorno',
        'metodo_pagamento',
        'domanda_cauzione_18',
        'cauzione_locazione_18',
        'domanda_spese_condominiali_8',
        'spese_5',
        'domanda_utenze_13',
        'utenze_27',
        'garanzie_accessorie_7',
        'domanda_garante_2',
        'cedolare_secca_12',
        'preavviso_recesso_conduttore_2_1',
        'mobilio_14',
        'domanda_elenco_arredi_intero_18',
        'elenco_arredi_lista_intero_18',
        'blocco_immobile_59',
        'domanda_pertinenze_15',
        'domanda_ape_7',
        'numero_attestato_prestazione_energetica_1',
        'locatore_10',
        'conduttore_10',
        'domanda_note_60',
        'note_59',
      ],
      step4: ['tipologia_contratto_18', 'domanda_arredi_1', 'domanda_note_34', 'note_34_5_1_1_1_2_1_1_1'],
    },
    'locazione-studenti-universitari': {
      step3: [
        'corso_di_studi_2_1',
        'durata_mesi_2_1_1',
        'data_decorrenza_locazione_3_1_3_1_2_2_1_1',
        'importo_mensile_locazione_10',
        'pagamento_canone_giorno_2_1_1',
        'metodo_pagamento_32',
        'domanda_cauzione_17',
        'cauzione_locazione_16',
        'domanda_spese_condominiali_4',
        'spese_6_1_1',
        'domanda_utenze_9',
        'utenze_18',
        'garanzie_accessorie_7_2_1_1',
        'domanda_garante_13',
        'domanda_recesso_conduttore_6',
        'preavviso_recesso_conduttore_2_1_2_1_1',
        'cedolare_secca_14_1_1',
        'mobilio_14_2_1_1',
        'domanda_elenco_arredi_intero_29',
        'elenco_arredi_lista_intero_29',
        'blocco_immobile_44',
        'domanda_pertinenze_15_2_1_1',
        'pertinenze_23_2_1_1',
        'domanda_ape_8',
        'numero_attestato_prestazione_energetica_1_2_1_1',
        'locatore_10_2_1_1',
        'conduttore_10_2_1_1',
        'domanda_note_57',
        'note_56',
      ],
      step4: ['tipologia_contratto_18', 'domanda_arredi_1', 'domanda_note_34', 'note_34_5_1_1_1_2_1_1_1'],
    },
  },
};

/** Step 4 requireds by city (all types share same creation form per city) */
export const REQUIRED_STEP4_BY_CITY: Record<City, string[]> = {
  milano: REQUIRED_REGISTRY.milano['locazione-3-2-canone'].step4,
  roma: REQUIRED_REGISTRY.roma['locazione-3-2-canone'].step4,
  torino: REQUIRED_REGISTRY.torino['locazione-3-2-canone'].step4,
};
