export type City = 'milano' | 'roma' | 'torino';
export type ContractType =
  | 'locazione-3-2-canone'
  | 'locazione-transitoria-canone'
  | 'locazione-studenti-universitari';

export interface RequiredSpec {
  step3: string[];
  step4: string[];
}

/** Baseline requireds compiled from the specs you pasted. */
export const REQUIRED_REGISTRY: Record<City, Record<ContractType, RequiredSpec>> = {
  milano: {
    'locazione-3-2-canone': {
      step3: [
        'tipologia_locazione_11_5',
        'durata_anni_2_6',
        'data_decorrenza_locazione_3_1_3_3_6',
        'importo_mensile_locazione_6_5',
        'pagamento_canone_3_2_6',
        'metodo_pagamento_34_6',
        'domanda_spese_condominiali_1_5',
        'domanda_utenze_6_3',
        'domanda_cauzione_15_5',
        'garanzie_accessorie_5_2_6',
        'domanda_recesso_conduttore_2_4',
        'cedolare_secca_6_7',
        'domanda_ape_1_5',
        'locatore_4_3_6',
        'conduttore_4_3_6',
        'blocco_immobile_29',
        'luogo_di_sottoscrizione_contratto_4_2_6',
        'data_di_sottoscrizione_contratto_4_2_6',
      ],
      step4: [
        'tipologia_locazione_20_4',
        'tipologia_contratto_14_5',
        'domanda_arredi_12',
        'domanda_note_22_5',
      ],
    },
    'locazione-transitoria-canone': {
      step3: [
        'locazione_intera_o_parziale_8_2_6',
        'esigenza_transitorieta_1_2_6',
        'durata_mesi_2_7',
        'data_decorrenza_locazione_3_1_3_1_2_2_7',
        'importo_mensile_locazione_5_5',
        'pagamento_canone_giorno_2_7',
        'metodo_pagamento_33_6',
        'domanda_spese_condominiali_5_5',
        'domanda_utenze_15_3',
        'domanda_cauzione_14_5',
        'garanzie_accessorie_7_2_7',
        'cedolare_secca_14_7',
        'preavviso_recesso_conduttore_2_1_2_7',
        'mobilio_14_2_7',
        'domanda_ape_13',
        'locatore_10_2_7',
        'conduttore_10_2_7',
        'blocco_immobile_51',
        'luogo_di_sottoscrizione_contratto_3_1_2_7',
        'data_di_sottoscrizione_contratto_3_1_2_7',
      ],
      step4: [
        'tipologia_locazione_20_4',
        'tipologia_contratto_14_5',
        'domanda_arredi_12',
        'domanda_note_22_5',
      ],
    },
    'locazione-studenti-universitari': {
      step3: [
        'locazione_intera_o_parziale_8_2_1_6',
        'corso_di_studi_2_8',
        'durata_mesi_2_1_8',
        'data_decorrenza_locazione_3_1_3_1_2_2_1_7',
        'importo_mensile_locazione_4_6',
        'pagamento_canone_giorno_2_1_8',
        'metodo_pagamento_35_7',
        'domanda_cauzione_13_6',
        'domanda_spese_condominiali_6_6',
        'domanda_utenze_8_3',
        'garanzie_accessorie_7_2_1_8',
        'domanda_recesso_conduttore_5_5',
        'preavviso_recesso_conduttore_2_1_2_1_7',
        'cedolare_secca_14_1_8',
        'mobilio_14_2_1_8',
        'domanda_ape_2_5',
        'locatore_10_2_1_8',
        'conduttore_10_2_1_8',
        'blocco_immobile_38',
        'luogo_di_sottoscrizione_contratto_3_1_2_1_8',
        'data_di_sottoscrizione_contratto_3_1_2_1_8',
      ],
      step4: [
        'tipologia_locazione_20_4',
        'tipologia_contratto_14_5',
        'domanda_arredi_12',
        'domanda_note_22_5',
      ],
    },
  },

  roma: {
    'locazione-3-2-canone': {
      step3: [
        'tipologia_locazione_11',
        'durata_anni_2',
        'data_decorrenza_locazione_3_1_3_3',
        'importo_mensile_locazione_6',
        'pagamento_canone_3_2',
        'metodo_pagamento_34',
        'domanda_spese_condominiali_1',
        'domanda_utenze_6',
        'domanda_cauzione_15',
        'garanzie_accessorie_5_2',
        'domanda_recesso_conduttore_2',
        'recesso_conduttore_1_2',
        'cedolare_secca_6',
        'domanda_ape_1',
        'locatore_4_3',
        'conduttore_4_3',
        'blocco_immobile_24',
        'luogo_di_sottoscrizione_contratto_4_2',
        'data_di_sottoscrizione_contratto_4_2',
      ],
      step4: ['tipologia_locazione_20', 'tipologia_contratto_14', 'domanda_arredi', 'domanda_note_22'],
    },
    'locazione-transitoria-canone': {
      step3: [
        'locazione_intera_o_parziale_8_2',
        'esigenza_transitorieta_1_2',
        'durata_mesi_2',
        'data_decorrenza_locazione_3_1_3_1_2_2',
        'importo_mensile_locazione_5',
        'pagamento_canone_giorno_2',
        'metodo_pagamento_33',
        'domanda_spese_condominiali_5',
        'domanda_utenze_15',
        'domanda_cauzione_14',
        'garanzie_accessorie_7_2',
        'cedolare_secca_14',
        'preavviso_recesso_conduttore_2_1_2',
        'mobilio_14_2',
        'domanda_ape',
        'locatore_10_2',
        'conduttore_10_2',
        'blocco_immobile_58'
      ],
      step4: ['tipologia_locazione_20', 'tipologia_contratto_14', 'domanda_arredi', 'domanda_note_22'],
    },
    'locazione-studenti-universitari': {
      step3: [
        'locazione_intera_o_parziale_8_2_1',
        'corso_di_studi_2',
        'durata_mesi_2_1',
        'data_decorrenza_locazione_3_1_3_1_2_2_1',
        'importo_mensile_locazione_4',
        'pagamento_canone_giorno_2_1',
        'metodo_pagamento_35',
        'domanda_cauzione_13',
        'domanda_spese_condominiali_6',
        'domanda_utenze_8',
        'garanzie_accessorie_7_2_1',
        'domanda_recesso_conduttore_5',
        'preavviso_recesso_conduttore_2_1_2_1',
        'cedolare_secca_14_1',
        'mobilio_14_2_1',
        'domanda_ape_2',
        'locatore_10_2_1',
        'conduttore_10_2_1',
        'blocco_immobile_45',
        'luogo_di_sottoscrizione_contratto_3_1_2_1',
        'data_di_sottoscrizione_contratto_3_1_2_1'
      ],
      step4: ['tipologia_locazione_20', 'tipologia_contratto_14', 'domanda_arredi', 'domanda_note_22'],
    },
  },

  torino: {
    'locazione-3-2-canone': {
      step3: [
        'durata_anni',
        'data_decorrenza_locazione_3_1_3',
        'importo_mensile_locazione_12',
        'pagamento_canone_3',
        'metodo_pagamento_31',
        'domanda_spese_condominiali_2',
        'domanda_utenze_2',
        'domanda_cauzione_19',
        'garanzie_accessorie_5',
        'domanda_recesso_conduttore_1',
        'recesso_conduttore_1',
        'cedolare_secca_17',
        'mobilio_12',
        'domanda_ape_6',
        'locatore_4',
        'conduttore_4',
        'blocco_immobile_30'
      ],
      step4: ['tipologia_contratto_18', 'domanda_arredi_1', 'domanda_note_34'],
    },
    'locazione-transitoria-canone': {
      step3: [
        'esigenza_transitorieta_1',
        'durata_mesi',
        'data_decorrenza_locazione_3_1_3_1_2',
        'importo_mensile_locazione_11',
        'pagamento_canone_giorno',
        'metodo_pagamento',
        'domanda_cauzione_18',
        'domanda_spese_condominiali_8',
        'domanda_utenze_13',
        'garanzie_accessorie_7',
        'cedolare_secca_12',
        'preavviso_recesso_conduttore_2_1',
        'mobilio_14',
        'domanda_ape_7',
        'locatore_10',
        'conduttore_10',
        'blocco_immobile_59'
      ],
      step4: ['tipologia_contratto_18', 'domanda_arredi_1', 'domanda_note_34'],
    },
    'locazione-studenti-universitari': {
      step3: [
        'corso_di_studi_2_1',
        'durata_mesi_2_1_1',
        'data_decorrenza_locazione_3_1_3_1_2_2_1_1',
        'importo_mensile_locazione_10',
        'pagamento_canone_giorno_2_1_1',
        'metodo_pagamento_32',
        'domanda_cauzione_17',
        'domanda_spese_condominiali_4',
        'domanda_utenze_9',
        'garanzie_accessorie_7_2_1_1',
        'domanda_recesso_conduttore_6',
        'preavviso_recesso_conduttore_2_1_2_1_1',
        'cedolare_secca_14_1_1',
        'mobilio_14_2_1_1',
        'domanda_ape_8',
        'locatore_10_2_1_1',
        'conduttore_10_2_1_1',
        'blocco_immobile_44'
      ],
      step4: ['tipologia_contratto_18', 'domanda_arredi_1', 'domanda_note_34'],
    },
  },
};

/** Step 4 requireds by city (all types share same creation form per city) */
export const REQUIRED_STEP4_BY_CITY: Record<City, string[]> = {
  milano: REQUIRED_REGISTRY.milano['locazione-3-2-canone'].step4,
  roma: REQUIRED_REGISTRY.roma['locazione-3-2-canone'].step4,
  torino: REQUIRED_REGISTRY.torino['locazione-3-2-canone'].step4,
};
